# Generated by Django 5.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemperatureDataFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Filename of the uploaded data file.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the data file."
                    ),
                ),
                (
                    "data_file",
                    models.FileField(
                        help_text="The uploaded JSON data file.",
                        upload_to="temperature/uploads/",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the file was uploaded."
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Data File",
                "verbose_name_plural": "Temperature Data Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "measurement_date",
                    models.DateField(
                        help_text="The date of the temperature measurement."
                    ),
                ),
                (
                    "publish_time",
                    models.DateTimeField(
                        help_text="When the measurement was published."
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        help_text="The measured temperature in degrees Celsius."
                    ),
                ),
                (
                    "temperature_reference_average",
                    models.FloatField(
                        help_text="Historical average temperature for this date."
                    ),
                ),
                (
                    "temperature_reference_high",
                    models.FloatField(
                        help_text="Historical high temperature reference for this date."
                    ),
                ),
                (
                    "temperature_reference_low",
                    models.FloatField(
                        help_text="Historical low temperature reference for this date."
                    ),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        help_text="The data file this reading was parsed from.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="temperature.temperaturedatafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Reading",
                "verbose_name_plural": "Temperature Readings",
                "ordering": ["measurement_date"],
                "unique_together": {("data_file", "measurement_date")},
            },
        ),
    ]