# Generated by Django 5.2.11 on 2026-02-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationDataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Filename of the uploaded data file.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the data file.')),
                ('data_file', models.FileField(help_text='The uploaded JSON data file.', upload_to='generation/uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the file was uploaded.')),
            ],
            options={
                'verbose_name': 'Generation Data File',
                'verbose_name_plural': 'Generation Data Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GenerationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The start time of the measurement period.')),
                ('settlement_period', models.IntegerField(help_text='The settlement period number.')),
                ('business_type', models.CharField(help_text='The business type (e.g., Production, Wind generation).', max_length=100)),
                ('psr_type', models.CharField(help_text='The power source type (e.g., Biomass, Solar, Wind Offshore).', max_length=100)),
                ('quantity', models.IntegerField(help_text='The generation quantity in MW.')),
                ('data_file', models.ForeignKey(help_text='The data file this reading was parsed from.', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='generation.generationdatafile')),
            ],
            options={
                'verbose_name': 'Generation Reading',
                'verbose_name_plural': 'Generation Readings',
                'ordering': ['start_time', 'psr_type'],
            },
        ),
    ]
